# Generated by Django 4.2.23 on 2025-08-19 16:02

import django.core.serializers.json
from django.db import migrations, models
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('extras', '0115_scheduledjob_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField()),
                ('severity', models.CharField(default='None', max_length=255)),
                ('cvss', models.FloatField(blank=True, null=True)),
                ('affected_softwares', models.ManyToManyField(blank=True, related_name='corresponding_cves', to='dcim.softwareversion')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'CVE',
                'ordering': ('severity', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
